version: "3"
services:
  app:
    image: nginx:latest
    container_name: "graph_web"
    ports:
      - "18080:80"
    volumes:
      - ./src:/app
      - ./logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf